services:
  cpp-sandbox:
    build:
      context: .
      dockerfile: Docker/cpp
    image: rce-cpp-sandbox

  server:
    build: ./server
    ports:
      - "4000:4000"
    environment:
      PORT: "4000"
      USE_DOCKER: "true"
      DOCKER_IMAGE: rce-cpp-sandbox
      DOCKER_VOLUME_NAME: rce-temp-vol
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - rce-temp-vol:/app/temp
    depends_on:
      - cpp-sandbox

  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      VITE_SERVER_URL: http://localhost:4000
    depends_on:
      - server

volumes:
  rce-temp-vol:
